# Generated by Django 6.0.1 on 2026-01-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_jobapplication_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'permissions': [('can_mark_employed', 'Can mark job as employed'), ('can_approve_leave', 'Can approve leave status')]},
        ),
    ]
